/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/value/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_value_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/value/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Players
         * @description The 661-row list, filtered as the Streamlit app filters it.
         *
         *     Sub-threshold players are included on purpose. They are in the dropdown so
         *     the refusal can be shown; removing them would hide the limitation rather
         *     than communicate it.
         */
        get: operations["players_api_value_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/value/players/{player_id}/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate */
        get: operations["estimate_api_value_players__player_id__estimate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_match_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seasons
         * @description Only seasons with held-out forecasts, matching the Streamlit app,
         *     which inner-joins its match table to the OOF table.
         */
        get: operations["seasons_api_match_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matches
         * @description Fixture list for the Season -> Club -> Match chain.
         *
         *     Restricted to matches that have a forecast. A bookmarked game_id outside
         *     that set still resolves (see below); it is simply not offered here.
         */
        get: operations["matches_api_match_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clubs */
        get: operations["clubs_api_match_clubs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/matches/{game_id}/held-out-forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Held Out Forecast */
        get: operations["held_out_forecast_api_match_matches__game_id__held_out_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/style/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_style_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/style/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Players
         * @description Filters on ANY listed position, not the first.
         *
         *     84 of the 315 players carry two (MF,FW and the like). First-token matching
         *     would hide 30 forwards from a client filtering on FW, which is how the
         *     Streamlit app behaves and must be reproduced exactly (AGENTS.md 5).
         */
        get: operations["players_api_style_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/style/players/{slug}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignment */
        get: operations["assignment_api_style_players__slug__assignment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Assignment */
        Assignment: {
            /** Cluster */
            cluster: number;
            /** Cluster Name */
            cluster_name: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "CONTESTED" | "BORDERLINE" | "PLACED";
            /** Distance To Centroid */
            distance_to_centroid: number;
            /** Distance To Rival */
            distance_to_rival: number;
            /** Margin To Next */
            margin_to_next: number;
            /** Silhouette */
            silhouette: number;
            /** Negative Silhouette */
            negative_silhouette: boolean;
            /** Rival Cluster */
            rival_cluster: number;
            /** Rival Cluster Name */
            rival_cluster_name: string;
            /** Position Adjacent */
            position_adjacent: boolean;
            cluster_position_share: components["schemas"]["ClusterPositionShare"];
        };
        /** Axis */
        Axis: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Value */
            value: number;
            /** Zones */
            zones: components["schemas"]["Zone"][];
        };
        /** Baseline */
        Baseline: {
            /** Always Home Accuracy */
            always_home_accuracy: number;
            /**
             * Label
             * @default always predict home win
             */
            label: string;
        };
        /** Caveat */
        Caveat: {
            /**
             * Key
             * @enum {string}
             */
            key: "blind_spot" | "veteran";
            /** Detail */
            detail?: string | null;
        };
        /** ClusterPositionShare */
        ClusterPositionShare: {
            /** Dominant */
            dominant: string;
            /** Share */
            share: number;
            /** N */
            n: number;
        };
        /** Coverage */
        Coverage: {
            /** Seasons Available */
            seasons_available: number[];
            /** Matches Available */
            matches_available: number;
            /** Matches Total */
            matches_total: number;
            /** Reason Key */
            reason_key: string;
        };
        /** Forecast */
        Forecast: {
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /**
             * Order
             * @description Fixed H, D, A. Served rather than inferred so that DESIGN.md's no-sorted-segments rule is a contract term.
             */
            order: string[];
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Top Pick */
            top_pick: string;
            /** Trained On Seasons */
            trained_on_seasons: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeldOutForecastResponse */
        HeldOutForecastResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "out_of_scope";
            /**
             * Source
             * @default precomputed_out_of_fold
             * @enum {string}
             */
            source: "model_inference" | "precomputed_out_of_fold" | "precomputed_assignment";
            /**
             * Computed At Request Time
             * @description Always false. AGENTS.md section 2.1 forbids calling the model per request; this restates it where a developer will see it. If it is ever true, the constraint broke.
             * @default false
             * @constant
             */
            computed_at_request_time: false;
            /** Reason */
            reason?: string | null;
            match: components["schemas"]["MatchSummary"];
            forecast?: components["schemas"]["Forecast"] | null;
            baseline?: components["schemas"]["Baseline"] | null;
            actual: components["schemas"]["MatchActual"];
            coverage?: components["schemas"]["Coverage"] | null;
            /** Form */
            form?: {
                [key: string]: components["schemas"]["SideForm"];
            } | null;
        };
        /** MatchActual */
        MatchActual: {
            /** Outcome */
            outcome: string;
            /** Top Pick Correct */
            top_pick_correct?: boolean | null;
        };
        /**
         * MatchListItem
         * @description The fixture list that drives the picker.
         *
         *     Typed rather than returned as a bare dict: this endpoint carries the
         *     game_id every forecast request is keyed on, and an untyped response means
         *     the generated client gets `additionalProperties: true` and no compile-time
         *     check on any field name. API.md §0's guarantee -- that the implementation
         *     and the contract cannot silently disagree -- only holds where a response
         *     model exists.
         */
        MatchListItem: {
            /** Game Id */
            game_id: number;
            /** Date */
            date: string;
            /** Season */
            season: number;
            /** Home Club */
            home_club: string;
            /** Away Club */
            away_club: string;
            /**
             * Venue
             * @description Set only when a club filter is applied; marks whether that club was home or away.
             */
            venue?: ("H" | "A") | null;
        };
        /** MatchSummary */
        MatchSummary: {
            /** Game Id */
            game_id: number;
            /** Date */
            date: string;
            /** Season */
            season: number;
            /** Matchday */
            matchday?: number | null;
            /** Home Club */
            home_club: string;
            /** Away Club */
            away_club: string;
        };
        /** Rate */
        Rate: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Group */
            group: string;
            /** Value */
            value: number;
            /** Percentile */
            percentile: number;
        };
        /** SideForm */
        SideForm: {
            /** Pre Ppg */
            pre_ppg?: number | null;
            /** Pre Position */
            pre_position?: number | null;
            /** Pts L5 */
            pts_l5?: number | null;
            /** Pts L10 */
            pts_l10?: number | null;
            /** Rest Days */
            rest_days?: number | null;
        };
        /** StyleAssignmentResponse */
        StyleAssignmentResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Source
             * @default precomputed_assignment
             * @enum {string}
             */
            source: "model_inference" | "precomputed_out_of_fold" | "precomputed_assignment";
            /** Player */
            player: {
                [key: string]: unknown;
            };
            /** Rates */
            rates: components["schemas"]["Rate"][];
            assignment: components["schemas"]["Assignment"];
            axis: components["schemas"]["Axis"];
        };
        /** StylePlayerListItem */
        StylePlayerListItem: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Club */
            club: string;
            /** Pos */
            pos: string;
            /** Minutes */
            minutes: number;
        };
        /** ToolMeta */
        ToolMeta: {
            /** Tool */
            tool: string;
            /** Model */
            model: string;
            /** Quality */
            quality: {
                [key: string]: unknown;
            };
            /**
             * Criteria
             * @default {}
             */
            criteria: {
                [key: string]: unknown;
            };
            /**
             * Coverage
             * @default {}
             */
            coverage: {
                [key: string]: unknown;
            };
            /**
             * Clusters
             * @default []
             */
            clusters: {
                [key: string]: unknown;
            }[];
            /**
             * Thresholds
             * @default {}
             */
            thresholds: {
                [key: string]: unknown;
            };
            /**
             * Plots
             * @default []
             */
            plots: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValueActual */
        ValueActual: {
            /** Market Value Eur */
            market_value_eur: number;
            /**
             * Inside Band
             * @description Computed server-side; the band's colour is the verdict, so it must not depend on client float arithmetic.
             */
            inside_band?: boolean | null;
        };
        /** ValueCalibration */
        ValueCalibration: {
            /** Field */
            field: string;
            /** Value */
            value: number;
            /** Minimum */
            minimum: number;
            /** Domain Min */
            domain_min: number;
            /** Domain Max */
            domain_max: number;
        };
        /** ValueEstimate */
        ValueEstimate: {
            /** Point Eur */
            point_eur: number;
            /** Low Eur */
            low_eur: number;
            /** High Eur */
            high_eur: number;
            /** Error Factor */
            error_factor: number;
            /**
             * Scale
             * @description The band is only meaningful on a log axis; values span EUR100k to EUR200m. A client rendering this linearly contradicts a field it was handed.
             * @default log10
             * @constant
             */
            scale: "log10";
        };
        /** ValueEstimateResponse */
        ValueEstimateResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "not_calibrated";
            /**
             * Source
             * @default model_inference
             * @enum {string}
             */
            source: "model_inference" | "precomputed_out_of_fold" | "precomputed_assignment";
            /** Reason */
            reason?: string | null;
            player: components["schemas"]["ValuePlayer"];
            /** Inputs */
            inputs?: {
                [key: string]: number;
            } | null;
            estimate?: components["schemas"]["ValueEstimate"] | null;
            actual: components["schemas"]["ValueActual"];
            calibration?: components["schemas"]["ValueCalibration"] | null;
            /**
             * Caveats
             * @default []
             */
            caveats: components["schemas"]["Caveat"][];
        };
        /** ValuePlayer */
        ValuePlayer: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Club */
            club: string;
            /** Position */
            position: string;
            /** Sub Position */
            sub_position?: string | null;
            /** Age */
            age: number;
            /** Pl Minutes */
            pl_minutes: number;
            /** Pl Matches */
            pl_matches: number;
        };
        /** ValuePlayerListItem */
        ValuePlayerListItem: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Club */
            club: string;
            /** Position */
            position: string;
            /** Pl Minutes */
            pl_minutes: number;
            /**
             * Eligible
             * @description False below min_pl_minutes. Such players stay in the list on purpose: removing them would hide the refusal rather than communicate it.
             */
            eligible: boolean;
        };
        /** Zone */
        Zone: {
            /** Name */
            name: string;
            /** From */
            from: number;
            /** To */
            to: number;
            /**
             * State
             * @enum {string}
             */
            state: "low" | "moderate" | "clear";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    meta_api_value_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMeta"];
                };
            };
        };
    };
    players_api_value_players_get: {
        parameters: {
            query?: {
                club?: string | null;
                position?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuePlayerListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_api_value_players__player_id__estimate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueEstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_match_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMeta"];
                };
            };
        };
    };
    seasons_api_match_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    matches_api_match_matches_get: {
        parameters: {
            query?: {
                season?: number | null;
                club?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clubs_api_match_clubs_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    held_out_forecast_api_match_matches__game_id__held_out_forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeldOutForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_style_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMeta"];
                };
            };
        };
    };
    players_api_style_players_get: {
        parameters: {
            query?: {
                position?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StylePlayerListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assignment_api_style_players__slug__assignment_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleAssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
